# Generated by Django 5.0 on 2023-12-30 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('roll_no', models.CharField(max_length=100)),
                ('dob', models.DateField(max_length=10)),
                ('blood_group', models.CharField(max_length=10)),
                ('father_name', models.CharField(max_length=100)),
                ('mother_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=12)),
                ('sem1_sgpa', models.CharField(max_length=5)),
                ('sem2_sgpa', models.CharField(max_length=5)),
                ('sem3_sgpa', models.CharField(max_length=5)),
                ('sem4_sgpa', models.CharField(max_length=5)),
                ('sem5_sgpa', models.CharField(max_length=5)),
                ('sem6_sgpa', models.CharField(max_length=5)),
                ('sem7_sgpa', models.CharField(max_length=5)),
                ('sem8_sgpa', models.CharField(max_length=5)),
            ],
        ),
    ]
