# Generated by Django 5.0 on 2024-01-07 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_student_email_student_gender_student_religion'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='image',
            field=models.ImageField(default='image.png', upload_to='images'),
            preserve_default=False,
        ),
    ]
