# Generated by Django 5.0 on 2024-01-07 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_student_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='avg_sgpa',
            field=models.FloatField(null=True),
        ),
    ]
